### 스테이지 등록
POST http://localhost:8080/api/stages
Content-Type: application/json

{
  "projectId": 1,
  "title": "스테이지 제목"
}

### 스테이지 전체 조회
GET http://localhost:8080/api/stages

### 스테이지 제목 수정
PUT http://localhost:8080/api/stages/1
Content-Type: application/json

{
  "title": "수정된 스테이지 제목"
}

### 스테이지 순서 이동
PUT http://localhost:8080/api/stages/1/position
Content-Type: application/json

{
  "position": 2
}

### 스테이지 삭제
DELETE http://localhost:8080/api/stages/1