### 값 미리 지정

# 일반 유저 정보 지정
@username = user1234
@password = Abcde1234!
@nickname = nickname
@email = user1@email.com

# 매니저 유저 정보 지정
@managerUsername = manager12
@managerNickname = managername
@managerEmail = manager1@email.com
@adminCode = S3cur3Adm!nK3y#456

@cardId = 1
@userId = 855445


### 회원가입 (일반)
POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}",
  "nickname": "{{nickname}}",
  "email": "{{email}}"
}


### 회원가입 (매니저)
POST http://localhost:8080/api/auth/sign-up
Content-Type: application/json

{
  "username": "{{managerUsername}}",
  "password": "{{password}}",
  "nickname": "{{managerNickname}}",
  "email": "{{managerEmail}}",
  "adminCode": "{{adminCode}}"
}


### 일반 유저 로그인 (토큰을 저장해서 다른테스트에 사용가능)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username":"{{username}}",
  "password":"{{password}}"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.global.set("X-Refresh-Token", response.headers.valueOf("X-Refresh-Token"));
%}


### 어드민 유저 로그인 (토큰을 저장해서 다른테스트에 사용가능)
POST http://localhost:8080/api/auth/login
Content-Type: application/json

{
  "username":"{{managerUsername}}",
  "password":"{{password}}"
}

> {%
  client.global.set("Authorization", response.headers.valueOf("Authorization"));
  client.global.set("X-Refresh-Token", response.headers.valueOf("X-Refresh-Token"));
%}

### 스테이지 등록
POST http://localhost:8080/api/stages
Content-Type: application/json
Authorization: {{Authorization}}

{
  "projectId": 1,
  "title": "스테이지 제목"
}


### 스테이지 전체 조회
GET http://localhost:8080/api/stages
Content-Type: application/json
Authorization: {{Authorization}}

### 스테이지 수정
PUT http://localhost:8080/api/stages/1
Content-Type: application/json
Authorization: {{Authorization}}

{
  "title": "수정된 스테이지 제목"
}

### 스테이지 순서 이동
PATCH http://localhost:8080/api/stages/1/position
Content-Type: application/json
Authorization: {{Authorization}}

{
  "position": 2
}

### 스테이지 삭제
DELETE http://localhost:8080/api/stages/1
Content-Type: application/json
Authorization: {{Authorization}}

### 카드 생성
POST http://localhost:8080/api/cards
Authorization: {{Authorization}}
Content-Type: application/json

{
  "stageId": 1,
  "title": "테스트",
  "content": "내용"
}

### 카드 생성
POST http://localhost:8080/api/cards
Authorization: {{Authorization}}
Content-Type: application/json

{
  "stageId": 1,
  "title": "테스트",
  "content": "내용",
  "userIdList": [
    1,
    2
  ]
}


### 단일조회
GET http://localhost:8080/api/cards/{{cardId}}


### 프로젝트내 모든 카드 조회
GET http://localhost:8080/api/cards?projectId=1


### 카드 수정
PUT http://localhost:8080/api/cards/{{cardId}}
Authorization: {{Authorization}}
Content-Type: application/json

{
  "title": "테스트",
  "content": "내용",
  "userIdList": [
    1,
    2
  ]
}


### 카드 삭제
DELETE http://localhost:8080/api/cards/9
Authorization: {{Authorization}}


### 카드 순서 이동
PUT http://localhost:8080/api/cards/{{cardId}}/position
Authorization: {{Authorization}}
Content-Type: application/json

{
  "stageId": 3,
  "newPosition": 1
}

### 댓글 생성
POST http://localhost:8080/api/comments
Content-Type: application/json
Authorization: {{Authorization}}

{
  "cardId": 1,
  "content": "댓글내용"
}

### 댓글 전체 조회
GET http://localhost:8080/api/comments
Content-Type: application/json
Authorization: {{Authorization}}

### 댓글 수정
PUT http://localhost:8080/api/comments/1
Content-Type: application/json
Authorization: {{Authorization}}

{
  "content": "수정된 댓글내용",
  "cardId": 1
}

### 댓글 삭제
DELETE http://localhost:8080/api/comments/1
Content-Type: application/json
Authorization: {{Authorization}}