### 댓글 생성
POST http://localhost:8080/api/comments
Content-Type: application/json

{
  "content": "댓글내용",
  "cardId": 1
}

### 댓글 전체 조회
GET http://localhost:8080/api/comments

### 댓글 수정
PUT http://localhost:8080/api/comments/1
Content-Type: application/json

{
  "content": "수정된 댓글내용",
  "cardId": 1
}

### 댓글 삭제
DELETE http://localhost:8080/api/comments/1